### ISSUE TITLE
Adjust portlet template to reflect current portlet setup

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/qube-cli#155]
The packages and classes should be set up comparable to the sampletracking-update-portlet

```
--life.qbic.portal.<portletname>
  |--DependencyManager.groovy
  |--PortletNameEntrypoint.groovy
  `-web
     |--Controller.groovy
     |--PortletView.groovy
     |--Presenter.groovy
     `--ViewModel.groovy
```

**Comment by Zethson** [comment]
@KochTobi 

This template can be found here: 
https://github.com/qbicsoftware/qube/tree/master/qube/create/templates/portlet/portlet_groovy/%7B%7B%20cookiecutter.project_slug%20%7D%7D

Since the sampletracking portlet already has some code and is not in a "template" state.

Would it be possible for you to either
1. Preferably submit a PR with your proposed new template structure?
Or 
2. Outline very detailed here what each of your files should contain?

I cannot guess from your structure what you're expecting (although I of course understand what Design Pattern you are after).

Cheers
