### ISSUE TITLE
Provide markdown support instead of rst

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/qube-cli#156]
**Is your feature request related to a problem? Please describe.**
RST documents are not rendered on GitHub nor in IntelliJ.

**Describe the solution you'd like**
Switch from README.rst back to README.md, same for the CHANGELOG.rst to CHANGELOG.md

**Comment by Zethson** [comment]
@KochTobi 
Github and IntelliJ render rst files. Just sometimes with bugs, because both use a custom parser and renderer for some weird reason.

Furthermore, we are defaulting to rst files, since our whole Read The Docs structure is based on *.rst files.

RTD defaults to rst. Markdown support exists, but would require quite a lot of work to actually get working as well and nicely as now.

Feel free to discuss this again with the team. If you are really dissatisfied with *.rst we can of course migrate.

Sorry for the late answer by the way. I didn't watch the repository, but will do so again, now.

Cheers.
